version: '3.9'

services:
  db:
    image: postgres
    platform: linux/amd64
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped  
    container_name: db
  server:
    platform: linux/amd64
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    depends_on:
     - db 
    ports:
      - '5001:5001'
      - '5000:5000'
    environment:
      PORT: 5001
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres'
  frontend:
    platform: linux/amd64
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
     - server   
    build:
      context: client
      dockerfile: Dockerfile