FROM node:alpine

# Create app directory
WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install
RUN npm install -g prisma
COPY . .
EXPOSE 5000
EXPOSE 5001
RUN chmod 777 startup.sh

CMD ["./startup.sh"]
